foreground   #c0c0c0
background   #1a1a1a
cursor       #a8a8a8

color0       #4a4a4a
color8       #6e6e6e
color1       #e06c75
color9       #ff7b86
color2       #7ECF6B
color10      #b5e890
color3       #e5c07b
color11      #ffd966
color4       #61afef
color12      #80c8ff
color5       #c678dd
color13      #e696ff
color6       #56b6c2
color14      #70d0dc
color7       #d4d4d4
color15      #ffffff
