# kitty +list-fonts [--psnames]
# https://sw.kovidgoyal.net/kitty/conf/#opt-kitty.font_features

font_family      MonoLisa-Regular
bold_font        MonoLisa-Bold
italic_font      MonoLisa-RegularItalic
bold_italic_font MonoLisa-BoldItalic
font_size 13.5

font_features MonoLisa-Regular       -zero -ss01 -ss02 -ss03 -ss04 +ss05 +ss07 +ss08 +ss10 +ss11 +ss12 +ss13 +ss14 -ss15 -ss16 +ss17 -ss18 +calt +liga
font_features MonoLisa-RegularItalic -zero -ss01 -ss02 -ss03 -ss04 +ss05 +ss07 +ss08 +ss10 +ss11 +ss12 +ss13 +ss14 -ss15 -ss16 +ss17 -ss18 +calt +liga
font_features MonoLisa-Bold          -zero -ss01 -ss02 -ss03 -ss04 +ss05 +ss07 +ss08 +ss10 +ss11 +ss12 +ss13 +ss14 -ss15 -ss16 +ss17 -ss18 +calt +liga
font_features MonoLisa-BoldItalic    -zero -ss01 +ss02 -ss03 -ss04 +ss05 +ss07 +ss08 +ss10 +ss11 +ss12 +ss13 +ss14 -ss15 -ss16 +ss17 -ss18 +calt +liga

cursor_trail 3000
cursor_trail_start_threshold 5

# terminal window
# cursor_blink_interval 0
background_opacity 0.8

include ~/.config/kitty/colorscheme.conf

# custom mappings
map super+shift+enter new_os_window_with_cwd

map ctrl+shift+d detach_tab ask

map kitty_mod+equal change_font_size current +2.0
map kitty_mod+minus change_font_size current -2.0

map ctrl+shift+p scroll_to_prompt -1
map ctrl+shift+n scroll_to_prompt 1
