# NOTE: scaling is not affected when applying new profile as long as
# it is not explicitly defined there

[[profile]]
name = "framework"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [{ search = "BOE", enable = true, scale = 1.175 }]


[[profile]]
name = "t14"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [{ search = "m=LP140WU4-SPK1", enable = true, scale = 1 }]


[[profile]]
name = "Iiyama"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [
    {search = "eDP-1", enable = false},
    {search = "PL3497WQP", enable = true, adaptive_sync = true, mode="3440x1440@100"},
]


[[profile]]
name = "arzopa-left"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [
    {search = "ARZOPA", enable = true, position = "0,0"},
    {search = "eDP-1", enable = true, position = "1920,0"},
]


[[profile]]
name = "arzopa-right"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [
    # works for both laptops since after scaling 2256 / 1.175 = 1920
    {search = "eDP-1", enable = true, position = "0,0"},
    {search = "ARZOPA", enable = true, position = "1920,0"},
]


[[profile]]
name = "office-left"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [
    {search = "m=P27h-20", enable = true, scale = 1, position = "0,0"},
    {search = "eDP-1", enable = true, scale = 1, position = "2560,0"},
]


[[profile]]
name = "office-right"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]
output = [
    {search = "eDP-1", enable = true, scale = 1, position = "0,0"},
    {search = "m=P27h-20", enable = true, scale = 1, position = "1920,0"},
]


[[profile]]
name = "dock"
exec = ["bash $HOME/.local/bin/shikane-notify.sh"]

    [[profile.output]]
    search = "eDP-1"
    enable = false

    [[profile.output]]
    enable = true
    search = ["v=AOC", "m=Q27G2G4"]
    mode = "2560x1440@60Hz"
    position = "0,0"

    [[profile.output]]
    enable = true
    # NOTE: on hyprland: "v=Xiaomi Corporation" whereas on sway: "v=XMI"
    search = ["v/Xiaomi Corporation|XMI", "m=Mi Monitor"]
    mode = "3440x1440@50Hz"
    position = "2560,0"
